### ISSUE TITLE
add action for tidythanks

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#128]
via `usethis::use_tidy_thanks()`.

**Comment by jimhester** [comment]
What is the use-case for this?

**Comment by maxheld83** [comment]
yeah, I guess that doesn't make a lot of sense, because `usethis::use_tidy_thanks()` would just be run as part of `pkgdown::build_site()` or wherever.
I copy-pasted lots of the tidyverse helpers here to get a sense of your workflow, but didn't think through whether each one actually required an *action*.

**Comment by jimhester** [comment]
We don't even use it in the pkgdown sites, it is only used interactively when writing the blog posts for releases. No worries, just didn't want you to do extra work!
