### ISSUE TITLE
get libssl from upstream images

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#174]
it appears that some package(s) (gh?) require libssl-dev to to be installed, and this appears not to be in the current r-hub image.

```
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because openssl was not found. Try installing:
 * deb: libssl-dev (Debian, Ubuntu, etc)
 * rpm: openssl-devel (Fedora, CentOS, RHEL)
 * csw: libssl_dev (Solaris)
 * brew: openssl@1.1 (Mac OSX)
If openssl is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a openssl.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
```

**Comment by jimhester** [comment]
You shouldn't need to do this manually necessarily, rhub has a [sysreq](https://github.com/r-hub/sysreqs) db and package that is uses to install necessary system requirements.

@gaborcsardi is the way you would recommend doing it?

**Comment by maxheld83** [comment]
yes, I was planning on doing that in #164, but will postpone that a bit and keep this open as a reminder.

**Comment by gaborcsardi** [comment]
Yeah, you can use the sysreqs package to query the R-hub platforms, and support for other platforms is coming out soon. Or you can also use the web-service directly: https://sysreqs.r-hub.io/

**Comment by maxheld83** [comment]
(note to self: similar issue with necessary `RUN apt-get install -y --no-install-recommends libxml2-dev` for pkgdown.
