### ISSUE TITLE
factor out development helper image to other package or repo

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#224]
tracked in

https://github.com/ColinFay/r-ci/issues/4
https://github.com/ColinFay/r-ci/issues/3

**Comment by jimhester** [comment]
I in general don't think we need to do this, we already have things working pretty well as is.

**Comment by maxheld83** [comment]
(veery deep, Mariana-trench-deep backlog):

There are currently two things in ghactions, which seem to sit a little awkwardly / may be useful in other settings:

1. A docker image with development helpers installed (*remotes*, *covr* and friends).
2. A mechanism for isolating the library tree of these development helpers from the *actual* package dependencies. (This could be enhanced via #212 #223).

The two belong together because the docker image has to install the development helpers to some `R_LIBS_FOO`  directory that is *not* usually in `.libPaths()`.

Long term, it might be interesting to build a slim, good docker image for this purpose (or maybe just use r-hub), and spin these two things out in a separate package.

It should have an interface somewhat akin to *withr*, where you can run something like:

`isoload::with_devhelper(pkg = "remotes", code = {remotes::install_deps()})`

This would then under the hood load/unload the namespace from `R_LIBS_FOO`, *without* ever altering `lib.Paths()`.

**Comment by maxheld83** [comment]
(This isn't really what the above package from colin tries, so that's closed).

**Comment by maxheld83** [comment]
A confluence of unforeseen limitations / unintended interactions / footguns leads me to believe that I might have to do this, and perhaps sooner rather than later (though not before trying out more automation).

- the programmatic commits and other code review automatisation will require more and heavier dependencies (for the actions only).
- actions run quickly **only when published to docker hub using the [github actions action-builder](http://github.com/actions/action-builder)**.
  This is because the actions builder automatically *tags the images with all github refs* (branches, releases, commit shas), and *that* is the "hack" that the github actions runner use to find the correct cached *version* of an actions image.
  `uses = foo/zap@1.12`  etc. accepts arbitrary git refs, and *this* is how they version the images.
   I only understood this last week.
- Of course said speedup *does not* extend to *this* repo, where the actions are build and all called with `uses = ./foo/bar`, ie. dogfooded from the current git commit.
- Because building all the action images with their dependencies takes quite a lot of time, I've already hit the 60mins timeout occasionally.
  With a few more actions, I will hit it *always*.
- it's hard / unlikely to speed up the action builds using usual docker layer caching.
  While docker will cache `RUN Rscript -e "install.packages('foo')"` *layers*, it doesn't track or understand the *dependencies* of *foo*.
  So if another action installs *bar*, even though bar may have a lot of the same dependencies as *foo*, it'll start from scratch.
- The present pattern of using a base image, where I build a base image and avoid some of the duplicate installations, and use this as `FROM` in the later images won't work reliably because it can't be properly versioned and the versioning of github actions is silently circumvented #231. 

So I think the clean solution would be to create a repo with a dependency-helper image, based on `rhub/debian-gcc-release`, bake some of the development helpers into it, tag and push it with all git refs, and then `FROM: maxheld83/ghactions-base@1.1` etc that in all of the actions.

That way, 
- We get build times for this package way below 60mins
- we get clean versioning of the base image

Not working on this now or soon, but wanted to write down my thoughts before I forget.

**Comment by maxheld83** [comment]
@jimhester the actions are now based on https://github.com/maxheld83/r-ci, which is just `r-hub/debian-gcc-release` and most of the dev helpers.

I don't have any more plans for that anytime soon, just needed to source that out to a separate repo to cut down the build times here and for the above reasons.

Let me know if you'd like to migrate this into r-lib.
