### ISSUE TITLE
speed up dependency installation

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#232]
in setting up an example package for #228 I've now managed to run out of the 60mins to complete `remotes::install_deps()`.

That's not great.

(The package in question isn't great and has huge dependencies, but that could be expected for *some* users).

Maybe the performance will improve or there's some degradation right now, seems a bit harsh to run for over an hour on just package installation.

**Comment by maxheld83** [comment]
here's the timeout https://github.com/maxheld83/pensieve/commit/1ba973dddc7112247689372bfcab27745a2a36ff

**Comment by maxheld83** [comment]
confirmed; `install-deps` for such a relatively heavy package (again, it's a bad package) is up to ~35 minutes.
With some expensive tests, that can go above the 59 mins quickly.

Travis has 120mins, so that was more lenient.

**Comment by maxheld83** [comment]
Only thing I can think of to speed this up now might be to move to ubuntu and use [RutteR](https://launchpad.net/~marutter/+archive/ubuntu/rrutter)

**Comment by jimhester** [comment]
Actually travis has a hard limit of 50 minutes on a single build.

**Comment by maxheld83** [comment]
ah ok, so we're at least not any worse off.

Managed to the (heavy) example package to work now, with homegrown Google Cloud Storage caching, it's down to ~10mins.

**Comment by maxheld83** [comment]
obsolete or done in the new yml-based GitHub actions.
