### ISSUE TITLE
replace gert with system calls

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#233]

**Comment by jimhester** [comment]
This doesn't seem a high priority to me, the docker images should all have command line git installed so you can just rely on that for the limited git actions you need.

**Comment by maxheld83** [comment]
yup, I'm just using gert for now, but will probably just migrate to `system()` or *processx* to call git as you suggested.
gert also seems a bit too limited anyway.

I *am* writing the "business" logic of the programmatic commits in R, not bash.

**Comment by maxheld83** [comment]
gert doesn't work anyway because 

```
── 1. Error: can be detected (@test-prog_com.R#4)  ─────────────────────────────
libgit2 error in git_signature_default: config value 'user.name' was not found (7)
```

libgit2 is only required for gert, so it's not worth it to get this to work.
