### ISSUE TITLE
get rid of spurious docker error "no space left on device"

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#240]
For the nth time (every 1-2 days of dev), `docker build` (or `docker run`?) fails with:

```
base64: write error: No space left on device
```

Currently at least, I can only reproduce this from within `act`.
`docker build` *outside* of `act` still works fine, even when producing a big new image with invalidated layers.

This might be a duplicate of https://github.com/nektos/act/issues/60

The disk image on my machine is still within the assigned limit:

<img width="502" alt="Screenshot 2019-06-07 at 13 30 38" src="https://user-images.githubusercontent.com/5372770/59101183-7a982800-8928-11e9-8c5c-e406cd015b9e.png">

This size also checks out. `ls -la ~/Library/Containers/com.docker.docker/Data/vms/0`:

```
.rw-r--r--@  26G max  7 Jun 13:35 Docker.qcow2
```

The [usual suggestions](https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device) don't help/change much:

```
docker volume prune --force
```

> `Total reclaimed space: 0B`

```
docker container prune --force
```

> `Total reclaimed space: 439.2MB`

```
docker system prune --force
```

> `Total reclaimed space: 2.455GB`

This does not affect the error from `act`.

**Comment by maxheld83** [comment]
the only thing that currently helps is:

- `rm -rf  ~/Library/Containers/com.docker.docker/Data/vms/0/Docker.qcow2`
- restart the docker daemon
- download all upstream images from scratch

**Comment by maxheld83** [comment]
obsolete or done in the new yml-based GitHub actions.

**Comment by juliofalbo** [comment]
You can try:

```
docker rm $(docker ps -q -f 'status=exited')
docker rmi $(docker images -q -f "dangling=true")
```
