### ISSUE TITLE
github wont accept major version actions versions

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#323]
https://help.github.com/en/articles/about-actions#versioning-your-action and https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsuses seem to suggest that you can call actions by major versions:

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

> ```
>steps:    
>  - uses: actions/setup-node@74bc508 # Reference a specific commit
>  - uses: actions/setup-node@v1      # Reference the major version of a release   
>  - uses: actions/setup-node@v1.2    # Reference a minor version of a release  
>  - uses: actions/setup-node@master  # Reference a branch
>```

But this doesn't seem to work as per https://github.com/maxheld83/pandoc-example/commit/2f26dfd81f6b80ed3d0e9d9a5bab7cc85830b380/checks.

It appears this *only* works when there is a literal `v1` tag. 
An equivalent (as per semantic versioning?) `v1.0.0` tag won't work.

I'm now unclear whether, as seems implied by the docs, `uses: actions/setup-node@v1` *will* float up to, say, `v1.1.4` should that be released.

Would be nice to change the behavior here or clarify the docs.

**Comment by maxheld83** [comment]
wrote support

**Comment by jimhester** [comment]
The way I read the docs these would correspond to actual git tags and there is no concept in git about semantic versioning; it would be weird for them to include it IMHO.

**Comment by maxheld83** [comment]
Ah, got it.

You're saying

> Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

just means that some maintainer could update the, say `v2` release.

I thought something cleverer would be going on where `v2` would take whichever `v2.x.x` is highest.

**Comment by rohith** [comment]
> I thought something cleverer would be going on where v2 would take whichever v2.x.x is highest.

exactly my thought when I read the docs & this assumption caused my action to fail in prod until I updated the tag to `v1`

**Comment by maxheld83** [comment]
The behavior of GitHub Actions and best practices are now documented here: https://github.com/actions/toolkit/blob/master/docs/action-versioning.md

Bottom line: If you want `v2` to float to whatever `v2.x.x` is highest (= major version binding), the action developer has to tag the new release accordingly. 
Makes sense now.
