### ISSUE TITLE
translate DESCRIPTIONs to Dockerfile

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#55]
useful in all kinds of circumstances

**Comment by maelle** [comment]
is it what https://github.com/o2r-project/containerit does?

**Comment by maxheld83** [comment]
yes Thanks for the suggestion @maelle! I’m going to look into that though I’m still hoping for a simpler tool. Maybe I can just use the internals of remote or something to get it done.

**Comment by maxheld83** [comment]
this is also on backlog for now, because for now, we're accepting *either* a `DESCRIPTION` (which `remotes::` can deal with just fine), *or* a `Dockerfile` with packages specified.

**Comment by maxheld83** [comment]
.. unless, of course, we can't find another way to have github actions cache images as per #3

**Comment by maxheld83** [comment]
pretty sure now this is not a great idea; if people have `DESCRIPTIONS`, we'll just `remotes::` that.
