### ISSUE TITLE
find better list of packages already in verse etc

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#60]
having to open the thing is too slow.

**Comment by VerenaHeld** [comment]
unable to find, write an issue to rocker.

**Comment by maxheld83** [comment]
something like this seems to already have been solved in https://github.com/o2r-project/containerit/issues/93

**Comment by maxheld83** [comment]
also, there is a question of whether this shouldn't actually be transferred over to the nascent [byod](https://github.com/maxheld83/byod)

**Comment by maxheld83** [comment]
this no longer makes much sense with the current actions/workflows. Just use remotes.
