### ISSUE TITLE
Use remotes directly rather than devtools

### ISSUE THREAD

**Issue by jimhester** [r-lib/ghactions#69]
While using docker container frees you from worrying about a lot of the dependency headaches of travis, you don't really need all of devtools installed. 

Instead I would recommend using `R CMD build` to build the package, `remotes` to do the dependency installation, and if you want pretty check output the `rcmdcheck` package.

**Comment by maxheld83** [comment]
thanks @jimhester that's great advice.

I actually haven't thought through how to best use GitHub actions for *packages* yet; I just threw the `main.workflow` for *this* package together real quickly.

Hope to get to that soon, but I thought I'd start with the easier *down projects.

**Comment by maxheld83** [comment]
this is part of #2
