### ISSUE TITLE
pass on environment variables between actions

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#89]
currently you have to write to disc for this.

asked github about it.

> I'm having a bit of a hard time passing on state between different actions in a workflow.
> 
> I know the disc persists, but it's really cumbersome to write simple would-be environment variables to disc, and to read them in again in later actions. Just feels weird.
> 
> I understand that *not* sharing just random environment variables and other states between actions is very much the point of github actions, but perhaps there can be some elegant way to export environment variables from one action to the other.
> 
> Perhaps with some additional syntax in the main.workflow, where I'd mark whatever env vars I'd like to *export* from an action to persist for downstream actions? (importing is already a feature, of course).
> 
> That'd be nice.
> 
> Or maybe I'm just using it wrong, in which case: please enlighten me!
> 
> Writing to disc just feels weird.

**Comment by maxheld83** [comment]
don't think this is going to happen.

**Comment by meeDamian** [comment]
Probably irrelevant forever already, but since I randomly stumbled upon this from Google, I'll leave a trace.

You can use:

```sh
echo ::set-env name=ENV_VAR_NAME::"env-var-value"
```

to set variable that's available from the next step onwards.

src: https://help.github.com/en/articles/development-tools-for-github-actions#set-an-environment-variable-set-env

**Comment by maxheld83** [comment]
thanks! This was actually about the old GitHub Actions (based on HCL).
