### ISSUE TITLE
migrate pkg to r-lib

### ISSUE THREAD

**Issue by maxheld83** [r-lib/ghactions#99]
@jimhester let me know if / whenever you'd like me to migrate this to the r-lib org; until then, I'm placing this on the backlog.
(I'm going to add RStudio as a funder in the `DESCRIPTION` etc, same as in the other r-lib pkgs as per #100).

**Comment by jimhester** [comment]
Sure we can move it now, it would make it a little easier for me to work on it. You should be able to do the transfer yourself in the settings.

**Comment by maxheld83** [comment]
Great!
I'll do this Friday after our call tomorrow; first want to get done with all the organising/prioritising.
